# Generated by Django 4.1.3 on 2023-08-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(choices=[('CC', 'CCKAGGLE'), ('CCP', 'CCPROCESSED')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConfusionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CM_LR_TP', models.IntegerField()),
                ('CM_LR_FP', models.IntegerField()),
                ('CM_LR_FN', models.IntegerField()),
                ('CM_LR_TN', models.IntegerField()),
                ('CM_RF_TP', models.IntegerField()),
                ('CM_RF_FP', models.IntegerField()),
                ('CM_RF_FN', models.IntegerField()),
                ('CM_RF_TN', models.IntegerField()),
                ('CM_SVM_TP', models.IntegerField()),
                ('CM_SVM_FP', models.IntegerField()),
                ('CM_SVM_FN', models.IntegerField()),
                ('CM_SVM_TN', models.IntegerField()),
                ('FileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC_Fraud_app.filename')),
            ],
        ),
        migrations.CreateModel(
            name='Accuracies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RandomForest', models.FloatField()),
                ('SVM', models.FloatField()),
                ('LogisticRegression', models.FloatField()),
                ('FileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC_Fraud_app.filename')),
            ],
        ),
    ]
