# Generated by Django 4.1.3 on 2023-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC_Fraud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuracies',
            name='LogisticRegression',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accuracies',
            name='RandomForest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accuracies',
            name='SVM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_LR_FN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_LR_FP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_LR_TN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_LR_TP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_RF_FN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_RF_FP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_RF_TN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_RF_TP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_SVM_FN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_SVM_FP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_SVM_TN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confusionmatrix',
            name='CM_SVM_TP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
